### PR TITLE
ui-components 'hammer' now has releases in npm

### PR DESCRIPTION
**Pull request by simaishi**

### CODE REVIEW

**Comment by Fryguy** [comment]
@simaishi Should this also be in master section for future releases?

**Comment by Fryguy** [comment]
I'm confused...why do we need the branch?  I thought has_real_releases avoids the need for the repo?

**Comment by simaishi** [comment]
The way @himdel explained to me was...  we need version number for npm, but each ui-components branch is tied to specific branch of manageiq-ui-classic (1.0.x for G, 1.1.x for H and 1.2.x for master).

So we will still need branches in ui-components when we cut manageiq branches and need yes/no labels for backport, but we don't want to tag (as it's not guaranteed tip of branch will be in the build until new release is cut, and ui-classic/ui-service is updated to use that new version).

At least that's my understanding...

**Comment by Fryguy** [comment]
I think the connection is loose though (that is, they just choose to keep G related to 1.0, H to 1.1, etc.).  However at the package level they link to a specific version number.  Are you saying that *sometimes* we depend on a random commit SHA and not version?

**Comment by simaishi** [comment]
No, for non-master, it's always a particular version (it's locked).

I guess what I was trying to say was... this is like any other repos for released gems, except we use a branch per manageiq release and we backport PRs.

**Pull request merged**
