### PR TITLE
Updates for kasparov

### PR DESCRIPTION
**Pull request by Fryguy**
@chessbyte Please review.

### CODE REVIEW

**Comment by chessbyte** [comment]
@Fryguy I think you missed the NSXT provider introduced with Kasparov

**Comment by Fryguy** [comment]
oh yeah good eyes

**Comment by chessbyte** [comment]
Why the file `config/repos.bluecf.yml` in this PR?

**Comment by Fryguy** [comment]
gah, I must have committed locally by accident :(

**Pull request merged**
