### PR TITLE
Remove labels for old versions we no longer plan to backport to

### PR DESCRIPTION
**Pull request by Fryguy**
@kbrock Please review.

### CODE REVIEW

**Comment by kbrock** [comment]
This looks good.

All the `yes?` should go to `yes` and to `backported` for PRs.
`conflict` should have been resolved back when we were considering backporting.

Keeping `no` and `backported` should be all the information we need.

The only tags of interest are in more recent branches:
- https://github.com/ManageIQ/manageiq/issues?q=label%3Amorphy%2Fyes+is%3Aclosed
- https://github.com/ManageIQ/manageiq/issues?q=label%3Amorphy%2Fyes%3F+is%3Aclosed
- https://github.com/ManageIQ/manageiq/issues?q=label%3Anajdorf%2Fyes%3F+is%3Aclosed

**Comment by Fryguy** [comment]
> Ok, so I heard you say:
> 
>   * All the `yes?` should go to `yes` and to `backported` for PRs. So there will be no need for `yes`, `yes?`.

should go to \*`no` or `backported`

> 
>   * `conflict` should have been resolved back when we were considering backporting, so there will be no need for old PRs with this label.
> 
>   * Keeping `no` and `backported` should be all the information we need.

Sounds right.

`yes?`, `yes`, and `conflict` are about "requesting backports".  `no` and `backported` are about "backport decisions and results".  We can drop the former if there is no longer a need to request, however the latter are a record of decision and its results.

**Comment by kbrock** [comment]
@Fryguy do you want to leave those old `/yes` tags on the merged PRs? mentioned above?

**Comment by Fryguy** [comment]
There shouldn't be /yes on merged PRs.  Where did you see those?

**Comment by kbrock** [comment]
see 3 links above

**Pull request merged**
