### PR TITLE
Add react-ui-components repo

### PR DESCRIPTION
**Pull request by Fryguy**
@simaishi Please review.

cc @martinpovolny This is why the milestone creator skipped this repo and it should work after this.

### CODE REVIEW

**Comment by simaishi** [comment]
Adding here means we'll also create branches, etc. for this repo. Is that what we're planning?

**Comment by martinpovolny** [comment]
@mzazrivec, @himdel: FYI

**Comment by himdel** [comment]
So, I guess with all the GTLs and toolbars, etc. in react-ui-components, we don't have much choice.

We can either have branches, or we need to split the release into a monorepo so that we're never updating react-ui-components for older releases, but only the specific thing.
(I think a monorepo is a good idea when backporting, but not as sure we wouldn't need the branches anyway. even with a monorepo.)

**Comment by Fryguy** [comment]
@himdel Not sure what your decision was here...are you ok with release branches (e.g. ivanchuk) being created, or should we set `has_real_releases: true` (implying we don't have release braches because you will cut proper npm packages with real release numbers).  Note that ui-components creates the release branches.

**Comment by chessbyte** [comment]
@Fryguy @himdel are we moving forward here or closing this PR?

**Comment by himdel** [comment]
We're halfway there.. https://github.com/ManageIQ/manageiq-ui-classic/issues/6716

**Pull request closed without merging**
